name: Docker Image CI

on:
  create:
    tags: [ v* ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        repository: ${{github.repository}}/generic-osb-api
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        add_git_labels: true
